### ISSUE TITLE
using 'cls' to clear screen

### ISSUE THREAD

**Issue by jmh666** [nikolajlauridsen/WordSearch#1]
$ ./wordsearch.py emphatic
    Googling that for you...
    Looking up source...
    sh: 1: cls: not found

added the following function to fix:

    def clear_screen():
        from os import name
        if name == "nt":
            clear = 'cls'
        else:
            clear = 'clear'
        return clear

then changed this line:

    os.system('cls')

to this:

    os.system(clear_screen())

**Comment by nikolajlauridsen** [comment]
Thanks a lot for your feed back, it's greatly appreciated, I've pushed a commit implementing your fix  👍
